### ISSUE TITLE
the button to open the command bar

### ISSUE THREAD

**Issue by JayduhNinja** [Not-Cyrus/Streets-Script#12]
whenever i try to open the command bar with ' it wont work but i'll give you some backstory. so first i got stuck in a building using healbot and blink then my body got disconnected then im inside a building that im not supposed to be in without noclip and the position i was in made it look like if i used noclip i'd fall(looking back i should've tried it man im dumb) then my command bar stopped working pls fix

**Comment by Not-Cyrus** [comment]
UID issue
