### ISSUE TITLE
Aimlock is broken

### ISSUE THREAD

**Issue by RegularID** [Not-Cyrus/Streets-Script#17]
At line 1306 and at line 1314, the if statements check for "AimLock" instead of the variable named "Aimlock". Please Fix. Also I don't use this script, just a friend of mine said it was broken.

![image](https://user-images.githubusercontent.com/69537751/125293150-d1546500-e32b-11eb-844c-af395299eab3.png)
![image](https://user-images.githubusercontent.com/69537751/125293109-c7326680-e32b-11eb-9805-4e0f65e3af7d.png)

**Comment by Not-Cyrus** [comment]
fixed jack updated the bypass and accidentally used the wrong name (this script never gets updated btw)
