### ISSUE TITLE
Script breaks on respawn

### ISSUE THREAD

**Issue by RegularID** [Not-Cyrus/Streets-Script#18]
At line 1294 you should make this in parentheses
![image](https://user-images.githubusercontent.com/69537751/127281700-9db717d1-c4a0-45f7-88c2-2e6e1f7f0451.png)
```lua
if (Method == 'WaitForChild' or Method == 'FindFirstChild') and getcaller() ~= script and TpBypass and Args[1] == 'HumanoidRootPart' then
```
if you do not put these on parentheses then it will check for every WaitForChild call and will cause errors like this
![image](https://user-images.githubusercontent.com/69537751/127282307-97bee425-1f8d-43ec-ad7c-99678ad35a95.png)

**Comment by Not-Cyrus** [comment]
there I did that ty
